// Code generated by sqlc-gen-poolroute. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

type PoolRouteQueries struct {
	reader *Queries
	writer *Queries
}

func NewPoolRouteQueries(writer DBTX, reader DBTX) *PoolRouteQueries {
	if reader == nil {
		reader = writer
	}
	return &PoolRouteQueries{
		reader: New(reader),
		writer: New(writer),
	}
}

func (poolroute *PoolRouteQueries) WithTx(tx pgx.Tx) *PoolRouteQueries {
	q := New(tx)
	return &PoolRouteQueries{
		reader: q,
		writer: q,
	}
}

func (poolroute *PoolRouteQueries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	return poolroute.writer.CreateAuthor(ctx, arg)
}

func (poolroute *PoolRouteQueries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	return poolroute.writer.CreateBook(ctx, arg)
}

func (poolroute *PoolRouteQueries) DeleteAuthor(ctx context.Context, id int64) error {
	return poolroute.writer.DeleteAuthor(ctx, id)
}

func (poolroute *PoolRouteQueries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	return poolroute.reader.GetAuthor(ctx, id)
}

func (poolroute *PoolRouteQueries) GetAuthorFromPrimary(ctx context.Context, id int64) (Author, error) {
	return poolroute.writer.GetAuthorFromPrimary(ctx, id)
}

func (poolroute *PoolRouteQueries) GetAuthorWithBooks(ctx context.Context, authorID int64) ([]GetAuthorWithBooksRow, error) {
	return poolroute.reader.GetAuthorWithBooks(ctx, authorID)
}

func (poolroute *PoolRouteQueries) GetBooksByAuthor(ctx context.Context, authorID int64) ([]GetBooksByAuthorRow, error) {
	return poolroute.reader.GetBooksByAuthor(ctx, authorID)
}

func (poolroute *PoolRouteQueries) ListAuthors(ctx context.Context) ([]Author, error) {
	return poolroute.reader.ListAuthors(ctx)
}

func (poolroute *PoolRouteQueries) LockAuthor(ctx context.Context, id int64) (Author, error) {
	return poolroute.writer.LockAuthor(ctx, id)
}

func (poolroute *PoolRouteQueries) TransferBooks(ctx context.Context, arg TransferBooksParams) error {
	return poolroute.writer.TransferBooks(ctx, arg)
}

func (poolroute *PoolRouteQueries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	return poolroute.writer.UpdateAuthor(ctx, arg)
}
