// Code generated by sqlc-pgx-route. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

// PoolRouteQueries routes read queries to a read replica and everything
// else (writes, :copyfrom, :batch) to the primary. The embedded *Queries is
// the primary/writer; only read methods are overridden below.
type PoolRouteQueries struct {
	*Queries
	reader *Queries
}

// NewPoolRouteQueries builds a PoolRouteQueries. When reader is nil all queries use writer.
func NewPoolRouteQueries(writer DBTX, reader DBTX) *PoolRouteQueries {
	if reader == nil {
		reader = writer
	}
	return &PoolRouteQueries{Queries: New(writer), reader: New(reader)}
}

// WithTx runs every query on tx; a transaction is pinned to one connection,
// so reads and writes cannot be split across pools.
func (q *PoolRouteQueries) WithTx(tx pgx.Tx) *PoolRouteQueries {
	qq := New(tx)
	return &PoolRouteQueries{Queries: qq, reader: qq}
}

func (q *PoolRouteQueries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	return q.reader.GetAuthor(ctx, id)
}

func (q *PoolRouteQueries) GetAuthorWithBooks(ctx context.Context, authorID int64) ([]GetAuthorWithBooksRow, error) {
	return q.reader.GetAuthorWithBooks(ctx, authorID)
}

func (q *PoolRouteQueries) GetBooksByAuthor(ctx context.Context, authorID int64) ([]GetBooksByAuthorRow, error) {
	return q.reader.GetBooksByAuthor(ctx, authorID)
}

func (q *PoolRouteQueries) ListAuthors(ctx context.Context) ([]Author, error) {
	return q.reader.ListAuthors(ctx)
}
