// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
    name, bio
) VALUES (
    $1, $2
)
RETURNING id, name, bio
`

type CreateAuthorParams struct {
	Name string
	Bio  pgtype.Text
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, author_id, price
) VALUES (
    $1, $2, $3
)
RETURNING id, title, author_id, price, created_at
`

type CreateBookParams struct {
	Title    string
	AuthorID int64
	Price    pgtype.Numeric
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.AuthorID, arg.Price)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const getAuthorFromPrimary = `-- name: GetAuthorFromPrimary :one
SELECT id, name, bio FROM authors WHERE id = $1
`

// rw:write
func (q *Queries) GetAuthorFromPrimary(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorFromPrimary, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const getAuthorWithBooks = `-- name: GetAuthorWithBooks :many
WITH author_books AS (
    SELECT id, title, author_id, price, created_at FROM books WHERE author_id = $1
)
SELECT id, title, author_id, price, created_at FROM author_books
`

type GetAuthorWithBooksRow struct {
	ID        int64
	Title     string
	AuthorID  int64
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAuthorWithBooks(ctx context.Context, authorID int64) ([]GetAuthorWithBooksRow, error) {
	rows, err := q.db.Query(ctx, getAuthorWithBooks, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorWithBooksRow
	for rows.Next() {
		var i GetAuthorWithBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT b.id, b.title, b.author_id, b.price, b.created_at, a.name as author_name
FROM books b
JOIN authors a ON a.id = b.author_id
WHERE b.author_id = $1
ORDER BY b.created_at DESC
`

type GetBooksByAuthorRow struct {
	ID         int64
	Title      string
	AuthorID   int64
	Price      pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) GetBooksByAuthor(ctx context.Context, authorID int64) ([]GetBooksByAuthorRow, error) {
	rows, err := q.db.Query(ctx, getBooksByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByAuthorRow
	for rows.Next() {
		var i GetBooksByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Price,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthor = `-- name: LockAuthor :one
SELECT id, name, bio FROM authors WHERE id = $1 FOR UPDATE
`

// rw:write
func (q *Queries) LockAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRow(ctx, lockAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const transferBooks = `-- name: TransferBooks :exec
WITH moved AS (
    UPDATE books SET author_id = $2 WHERE author_id = $1 RETURNING id, title, author_id, price, created_at
)
SELECT count(*) FROM moved
`

type TransferBooksParams struct {
	AuthorID   int64
	AuthorID_2 int64
}

func (q *Queries) TransferBooks(ctx context.Context, arg TransferBooksParams) error {
	_, err := q.db.Exec(ctx, transferBooks, arg.AuthorID, arg.AuthorID_2)
	return err
}

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors
SET name = $2, bio = $3
WHERE id = $1
`

type UpdateAuthorParams struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	_, err := q.db.Exec(ctx, updateAuthor, arg.ID, arg.Name, arg.Bio)
	return err
}
